Pharmacies Management/Controllers/ItemsController.cs
using AutoMapper;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NToastNotify;
using PharmaciesManagement.Models;
using PharmaciesManagement.ViewModels;
using System.Threading.Tasks;

namespace PharmaciesManagement.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification _toastNotification;
        protected readonly IValidator<ItemViewModel> _validator;
        private readonly IMapper _mapper;
        private readonly ILogger<ItemsController> _logger;
        public ItemsController(ApplicationDbContext context, IToastNotification toastNotification, IValidator<ItemViewModel> validator, IMapper mapper, ILogger<ItemsController> logger)
        {
            _context = context;
            _toastNotification = toastNotification;
            _validator = validator;
            _mapper = mapper;
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            var items = await _context.Items.ToListAsync();
            return View(items);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = new ItemViewModel
            {
            };

            return View("ItemForm", viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ItemViewModel model)
        {
            ValidationResult validationResult = await _validator.ValidateAsync(model);
            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(this.ModelState);
                return View("ItemForm", model);
            }
            var item = _mapper.Map<Item>(model);

            _context.Items.Add(item);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("تم إنشاء الصنف بنجاح");
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return BadRequest();

            var item = await _context.Items.FindAsync(id);

            if (item == null)
                return NotFound();

            var viewModel = new ItemViewModel
            {
                Id = item.Id,
                Name = item.Name,
            };

            return View("ItemForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ItemViewModel model)
        {
            ValidationResult validationResult = await _validator.ValidateAsync(model);
            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(this.ModelState);
                return View("ItemForm", model);
            }

            var item = await _context.Items.FindAsync(model.Id);

            if (item == null)
                return NotFound();
            item.Name = model.Name;
            _context.SaveChanges();
            _toastNotification.AddSuccessToastMessage("تم تعديل الصنف بنجاح");
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();

            var item = await _context.Items.FindAsync(id);

            if (item == null)
                return NotFound();

            _context.Items.Remove(item);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Pharmacies Management/Controllers/PurchaseController.cs
using AutoMapper;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NToastNotify;
using PharmaciesManagement.Models;
using PharmaciesManagement.ViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace PharmaciesManagement.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification _toastNotification;
        protected readonly IValidator<PurchaseViewModel> _validator;
        private readonly IMapper _mapper;
        private readonly ILogger<PurchaseController> _logger;


        public PurchaseController(ApplicationDbContext context, IToastNotification toastNotification, IValidator<PurchaseViewModel> validator, IMapper mapper, ILogger<PurchaseController> logger)
        {
            _context = context;
            _toastNotification = toastNotification;
            _validator = validator;
            _mapper = mapper;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var purshase = await _context.Purchases.ToListAsync();

            return View(purshase);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = new PurchaseViewModel
            {
                Stores = await _context.Stores.OrderBy(m => m.Branch).ToListAsync(),
                Items = await _context.Items.OrderBy(m => m.Name).ToListAsync()
            };

            return View("PurchaseForm", viewModel);
        }
        public IActionResult GetBalance(int storeId, int itemId)
        {
            var balance = _context.Purchases.Where(s => s.StoreId == storeId && s.ItemId == itemId).Sum(q => q.Quantity);
            return Ok(balance);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PurchaseViewModel model)
        {
            ValidationResult validationResult = await _validator.ValidateAsync(model);
            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(this.ModelState);
                model.Stores = await _context.Stores.OrderBy(m => m.Branch).ToListAsync();
                model.Items = await _context.Items.OrderBy(m => m.Name).ToListAsync();
                return View("PurchaseForm", model);
            }
            var purchase = _mapper.Map<Purchase>(model);
            _context.Purchases.Add(purchase);
            _context.SaveChanges();
            _toastNotification.AddSuccessToastMessage("تم إنشاء المشتريات بنجاح");
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();

            var purchase = await _context.Purchases.FindAsync(id);

            if (purchase == null)
                return NotFound();

            _context.Purchases.Remove(purchase);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Pharmacies Management/Controllers/StoresController.cs
using AutoMapper;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NToastNotify;
using PharmaciesManagement.Models;
using PharmaciesManagement.ViewModels;
using System.Threading.Tasks;

namespace Pharmacies_Management.Controllers
{
    public class StoresController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification _toastNotification;
        protected readonly IValidator<StoreViewModel> _validator;
        private readonly IMapper _mapper;
        private readonly ILogger<StoresController> _logger;
        public StoresController(ApplicationDbContext context, IToastNotification toastNotification, IValidator<StoreViewModel> validator, IMapper mapper, ILogger<StoresController> logger)
        {
            _context = context;
            _toastNotification = toastNotification;
            _validator = validator;
            _mapper = mapper;
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            var stores = await _context.Stores.ToListAsync();
            return View(stores);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = new StoreViewModel
            {
            };

            return View("StoreForm", viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StoreViewModel model)
        {
            ValidationResult validationResult = await _validator.ValidateAsync(model);
            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(this.ModelState);
                return View("StoreForm", model);
            }
            var store = _mapper.Map<Store>(model);

            _context.Stores.Add(store);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("تم إنشاء الفرع بنجاح");
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return BadRequest();

            var store = await _context.Stores.FindAsync(id);

            if (store == null)
                return NotFound();

            var viewModel = new StoreViewModel
            {
                Id = store.Id,
                Branch = store.Branch,
            };

            return View("StoreForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(StoreViewModel model)
        {
            ValidationResult validationResult = await _validator.ValidateAsync(model);
            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(this.ModelState);
                return View("StoreForm", model);
            }

            var store = await _context.Stores.FindAsync(model.Id);

            if (store == null)
                return NotFound();
            store.Branch = model.Branch;
            _context.SaveChanges();
            _toastNotification.AddSuccessToastMessage("تم تعديل الفرع بنجاح");
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();

            var store = await _context.Stores.FindAsync(id);

            if (store == null)
                return NotFound();

            _context.Stores.Remove(store);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Pharmacies Management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - صيدليات العزبى</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pharmacies_Management.styles.css" asp-append-version="true" />
    <link href="~/lib/animate.css/animate.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">صيدليات العزبى</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">الصفحة الرئيسية</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">الخصوصية</a>
                        </li
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stores" asp-action="Index">الفروع</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">الأصناف</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Purchase" asp-action="Index">المشتريات</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - صيدليات العزبى - <a asp-area="" asp-controller="Home" asp-action="Privacy">الخصوصية</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootbox.js/bootbox.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>